### ISSUE TITLE
Rename "Tail Call Optimization" to "Guaranteed Tail Call Optimization"

### ISSUE THREAD

**Issue by gabriel-fallen** [cblp/funlangs#2]
Tail Call Optimization is possible in most languages and gets performed on many occasions by most mature compilers even for C and C++ or Scala for instance. Thus current statement is technically incorrect. I think we should clarify that we're talking about *guaranteed* TCO that's mandated by language standard and provided by all implementations of said language.

**Comment by cblp** [comment]
done
